/*
 * File: app/view/CreateAccount.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LoginApp.view.CreateAccount', {
    extend: 'Ext.Panel',
    alias: 'widget.createaccount',

    requires: [
        'LoginApp.view.CreateAccountViewModel',
        'Ext.Container',
        'Ext.field.Email',
        'Ext.field.Password',
        'Ext.Button'
    ],

    viewModel: {
        type: 'createaccount'
    },
    width: 320,
    centered: true,
    modal: true,
    title: 'Register for your account',

    items: [
        {
            xtype: 'container',
            padding: '10 5',
            defaults: {
                margin: 10
            },
            items: [
                {
                    xtype: 'textfield',
                    name: 'firstname',
                    scrollable: false,
                    label: 'First name',
                    required: true
                },
                {
                    xtype: 'textfield',
                    name: 'lastname',
                    label: 'Last name'
                },
                {
                    xtype: 'emailfield',
                    name: 'email',
                    label: 'Email (will be your username)',
                    required: true
                },
                {
                    xtype: 'passwordfield',
                    name: 'password',
                    label: 'Password',
                    required: true
                },
                {
                    xtype: 'passwordfield',
                    name: 'confpassword',
                    label: 'Confirm password',
                    required: true
                }
            ]
        },
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                align: 'center',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        this.up('panel').close();
                    },
                    ui: 'decline',
                    width: '50%',
                    text: 'Cancel'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        this.up('panel').close();
                        var userRegistered = Ext.create({
                            fullscreen: true,
                            xtype: 'panel',
                            centered: true,
                            height: 400,
                            width: 400,
                            padding: 10,
                            items: [{
                                style: 'font-size: 20px',
                                html: 'Registered Successfully'
                            }, {
                                padding: '25 0 25 0',
                                style: 'font-size: 14px',
                                html: 'Congratulations! You have successfully registered your account. Please follow the instructions sent to your email to activate your account, and proceed to login.'
                            }, {
                                xtype: 'container',
                                layout: {
                                    type: 'hbox',
                                    align: 'center',
                                    pack: 'center'
                                },
                                items: [{
                                    xtype: 'button',
                                    text: 'Back to Login',
                                    width: 200,
                                    cls: [
                                    'x-button-focus',
                                    'x-button-pressed'
                                    ],
                                    handler: function() {
                                        this.up('panel').close();
                                    }
                                }]
                            }]
                        });
                        userRegistered.show();
                    },
                    ui: 'confirm',
                    width: '50%',
                    text: 'Register'
                }
            ]
        }
    ]

});