/*
 * File: app/view/MyPanelViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Arch101.view.MyPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mypanel',

    onButtonTap: function(button, e, eOpts) {
        Ext.Ajax.request({
            url: 'http://localhost:8080/version',
            cors: true,
            success: function(response, opts) {
                var obj = Ext.decode(response.responseText);
                button.setText (obj.server.concat(" ", obj.version));
            },
        });
    }

});