--------------------------------------------------------------------------------
-- Embarcadero DB Change Manager Synchronization Script
-- FILE                : Schema-Archive-Job-ORA Sep 9, 2016 10_01_10 AM.sql
-- DATE                : Sep 9, 2016 10:01:11 AM
-- 
-- SOURCE DATA SOURCE  : FIREDAC-ORA
--------------------------------------------------------------------------------
CREATE SEQUENCE FIREDAC.CUSTOMER_SEQ
    START WITH 80
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    NOORDER
/
CREATE SEQUENCE FIREDAC.INVOICE_SEQ
    START WITH 412
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    NOORDER
/
CREATE TABLE FIREDAC.ALBUM
(
    ALBUMID  NUMBER        NOT NULL,
    TITLE    VARCHAR2(160) NOT NULL,
    ARTISTID NUMBER        NOT NULL,
    CONSTRAINT PK_ALBUM
    PRIMARY KEY (ALBUMID)
        USING INDEX TABLESPACE USERS
                    PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
CREATE TABLE FIREDAC.ARTIST
(
    ARTISTID NUMBER        NOT NULL,
    NAME     VARCHAR2(120)     NULL,
    CONSTRAINT PK_ARTIST
    PRIMARY KEY (ARTISTID)
        USING INDEX TABLESPACE USERS
                    PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE FIREDAC.ALBUM
    ADD CONSTRAINT FK_ALBUMARTISTID
    FOREIGN KEY (ARTISTID)
    REFERENCES FIREDAC.ARTIST (ARTISTID)
    ENABLE
    VALIDATE
/
CREATE TABLE FIREDAC.CUSTOMER
(
    CUSTOMERID   NUMBER       NOT NULL,
    FIRSTNAME    VARCHAR2(40) NOT NULL,
    LASTNAME     VARCHAR2(20) NOT NULL,
    COMPANY      VARCHAR2(80)     NULL,
    ADDRESS      VARCHAR2(70)     NULL,
    CITY         VARCHAR2(40)     NULL,
    STATE        VARCHAR2(40)     NULL,
    COUNTRY      VARCHAR2(40)     NULL,
    POSTALCODE   VARCHAR2(10)     NULL,
    PHONE        VARCHAR2(24)     NULL,
    FAX          VARCHAR2(24)     NULL,
    EMAIL        VARCHAR2(60) NOT NULL,
    SUPPORTREPID NUMBER           NULL,
    CONSTRAINT PK_CUSTOMER
    PRIMARY KEY (CUSTOMERID)
        USING INDEX TABLESPACE USERS
                    PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
CREATE OR REPLACE TRIGGER FIREDAC.CUSTOMER_BI
BEFORE INSERT
ON FIREDAC.CUSTOMER
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
IF :NEW.CUSTOMERID IS NULL THEN
    SELECT CUSTOMER_SEQ.NEXTVAL INTO :NEW.CUSTOMERID FROM DUAL;
END IF;
END;
/
CREATE TABLE FIREDAC.EMPLOYEE
(
    EMPLOYEEID NUMBER       NOT NULL,
    LASTNAME   VARCHAR2(20) NOT NULL,
    FIRSTNAME  VARCHAR2(20) NOT NULL,
    TITLE      VARCHAR2(30)     NULL,
    REPORTSTO  NUMBER           NULL,
    BIRTHDATE  DATE             NULL,
    HIREDATE   DATE             NULL,
    ADDRESS    VARCHAR2(70)     NULL,
    CITY       VARCHAR2(40)     NULL,
    STATE      VARCHAR2(40)     NULL,
    COUNTRY    VARCHAR2(40)     NULL,
    POSTALCODE VARCHAR2(10)     NULL,
    PHONE      VARCHAR2(24)     NULL,
    FAX        VARCHAR2(24)     NULL,
    EMAIL      VARCHAR2(60)     NULL,
    CONSTRAINT PK_EMPLOYEE
    PRIMARY KEY (EMPLOYEEID)
        USING INDEX TABLESPACE USERS
                    PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE FIREDAC.CUSTOMER
    ADD CONSTRAINT FK_CUSTOMERSUPPORTREPID
    FOREIGN KEY (SUPPORTREPID)
    REFERENCES FIREDAC.EMPLOYEE (EMPLOYEEID)
    ENABLE
    VALIDATE
/
ALTER TABLE FIREDAC.EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEEREPORTSTO
    FOREIGN KEY (REPORTSTO)
    REFERENCES FIREDAC.EMPLOYEE (EMPLOYEEID)
    ENABLE
    VALIDATE
/
CREATE TABLE FIREDAC.GENRE
(
    GENREID NUMBER        NOT NULL,
    NAME    VARCHAR2(120)     NULL,
    CONSTRAINT PK_GENRE
    PRIMARY KEY (GENREID)
        USING INDEX TABLESPACE USERS
                    PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
CREATE TABLE FIREDAC.INVOICE
(
    INVOICEID         NUMBER       NOT NULL,
    CUSTOMERID        NUMBER       NOT NULL,
    INVOICEDATE       DATE         NOT NULL,
    BILLINGADDRESS    VARCHAR2(70)     NULL,
    BILLINGCITY       VARCHAR2(40)     NULL,
    BILLINGSTATE      VARCHAR2(40)     NULL,
    BILLINGCOUNTRY    VARCHAR2(40)     NULL,
    BILLINGPOSTALCODE VARCHAR2(10)     NULL,
    TOTAL             NUMBER(10,2) NOT NULL,
    CONSTRAINT PK_INVOICE
    PRIMARY KEY (INVOICEID)
        USING INDEX TABLESPACE USERS
                    PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
CREATE OR REPLACE TRIGGER FIREDAC.INVOICE_BI
BEFORE INSERT
ON FIREDAC.INVOICE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
IF :NEW.INVOICEID IS NULL THEN
    SELECT INVOICE_SEQ.NEXTVAL INTO :NEW.INVOICEID FROM DUAL;
END IF;
END;
/
ALTER TABLE FIREDAC.INVOICE
    ADD CONSTRAINT FK_INVOICECUSTOMERID
    FOREIGN KEY (CUSTOMERID)
    REFERENCES FIREDAC.CUSTOMER (CUSTOMERID)
    ENABLE
    VALIDATE
/
CREATE TABLE FIREDAC.INVOICELINE
(
    INVOICELINEID NUMBER       NOT NULL,
    INVOICEID     NUMBER       NOT NULL,
    TRACKID       NUMBER       NOT NULL,
    UNITPRICE     NUMBER(10,2) NOT NULL,
    QUANTITY      NUMBER       NOT NULL,
    CONSTRAINT PK_INVOICELINE
    PRIMARY KEY (INVOICELINEID)
        USING INDEX TABLESPACE USERS
                    PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE FIREDAC.INVOICELINE
    ADD CONSTRAINT FK_INVOICELINEINVOICEID
    FOREIGN KEY (INVOICEID)
    REFERENCES FIREDAC.INVOICE (INVOICEID)
    ENABLE
    VALIDATE
/
CREATE TABLE FIREDAC.MEDIATYPE
(
    MEDIATYPEID NUMBER        NOT NULL,
    NAME        VARCHAR2(120)     NULL,
    CONSTRAINT PK_MEDIATYPE
    PRIMARY KEY (MEDIATYPEID)
        USING INDEX TABLESPACE USERS
                    PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
CREATE TABLE FIREDAC.PLAYLIST
(
    PLAYLISTID NUMBER        NOT NULL,
    NAME       VARCHAR2(120)     NULL,
    CONSTRAINT PK_PLAYLIST
    PRIMARY KEY (PLAYLISTID)
        USING INDEX TABLESPACE USERS
                    PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
CREATE TABLE FIREDAC.PLAYLISTTRACK
(
    PLAYLISTID NUMBER NOT NULL,
    TRACKID    NUMBER NOT NULL,
    CONSTRAINT PK_PLAYLISTTRACK
    PRIMARY KEY (PLAYLISTID,TRACKID)
        USING INDEX TABLESPACE USERS
                    PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE FIREDAC.PLAYLISTTRACK
    ADD CONSTRAINT FK_PLAYLISTTRACKPLAYLISTID
    FOREIGN KEY (PLAYLISTID)
    REFERENCES FIREDAC.PLAYLIST (PLAYLISTID)
    ENABLE
    VALIDATE
/
CREATE TABLE FIREDAC.TRACK
(
    TRACKID      NUMBER        NOT NULL,
    NAME         VARCHAR2(200) NOT NULL,
    ALBUMID      NUMBER            NULL,
    MEDIATYPEID  NUMBER        NOT NULL,
    GENREID      NUMBER            NULL,
    COMPOSER     VARCHAR2(220)     NULL,
    MILLISECONDS NUMBER        NOT NULL,
    BYTES        NUMBER            NULL,
    UNITPRICE    NUMBER(10,2)  NOT NULL,
    CONSTRAINT PK_TRACK
    PRIMARY KEY (TRACKID)
        USING INDEX TABLESPACE USERS
                    PCTFREE 10
                    INITRANS 2
                    MAXTRANS 255
                    STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
)
ORGANIZATION HEAP
TABLESPACE USERS
LOGGING
PCTFREE 10
PCTUSED 0
INITRANS 1
MAXTRANS 255
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCACHE
NOROWDEPENDENCIES
/
ALTER TABLE FIREDAC.INVOICELINE
    ADD CONSTRAINT FK_INVOICELINETRACKID
    FOREIGN KEY (TRACKID)
    REFERENCES FIREDAC.TRACK (TRACKID)
    ENABLE
    VALIDATE
/
ALTER TABLE FIREDAC.PLAYLISTTRACK
    ADD CONSTRAINT FK_PLAYLISTTRACKTRACKID
    FOREIGN KEY (TRACKID)
    REFERENCES FIREDAC.TRACK (TRACKID)
    ENABLE
    VALIDATE
/
ALTER TABLE FIREDAC.TRACK
    ADD CONSTRAINT FK_TRACKALBUMID
    FOREIGN KEY (ALBUMID)
    REFERENCES FIREDAC.ALBUM (ALBUMID)
    ENABLE
    VALIDATE
/
ALTER TABLE FIREDAC.TRACK
    ADD CONSTRAINT FK_TRACKGENREID
    FOREIGN KEY (GENREID)
    REFERENCES FIREDAC.GENRE (GENREID)
    ENABLE
    VALIDATE
/
ALTER TABLE FIREDAC.TRACK
    ADD CONSTRAINT FK_TRACKMEDIATYPEID
    FOREIGN KEY (MEDIATYPEID)
    REFERENCES FIREDAC.MEDIATYPE (MEDIATYPEID)
    ENABLE
    VALIDATE
/
