--------------------------------------------------------------------------------
-- Embarcadero DB Change Manager Synchronization Script
-- FILE                : Schema-Archive-Job-IB Sep 9, 2016 9_53_06 AM.sql
-- DATE                : Sep 9, 2016 9:53:07 AM
-- 
-- SOURCE DATA SOURCE  : FIREDAC
--------------------------------------------------------------------------------
CREATE GENERATOR CUSTOMER_GEN
;
SET GENERATOR CUSTOMER_GEN TO 67
;
CREATE GENERATOR INVOICE_GEN
;
SET GENERATOR INVOICE_GEN TO 414
;
CREATE TABLE ARTIST
(
    ARTISTID integer      NOT NULL,
    NAME     varchar(120) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    CONSTRAINT PK_ARTIST
    PRIMARY KEY (ARTISTID)
)
;
CREATE TABLE ALBUM
(
    ALBUMID  integer      NOT NULL,
    TITLE    varchar(160) CHARACTER SET ISO8859_1 NOT NULL COLLATE ISO8859_1,
    ARTISTID integer      NOT NULL,
    CONSTRAINT PK_ALBUM
    PRIMARY KEY (ALBUMID)
)
;
CREATE TABLE EMPLOYEE
(
    EMPLOYEEID integer     NOT NULL,
    LASTNAME   varchar(20) CHARACTER SET ISO8859_1 NOT NULL COLLATE ISO8859_1,
    FIRSTNAME  varchar(20) CHARACTER SET ISO8859_1 NOT NULL COLLATE ISO8859_1,
    TITLE      varchar(30) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    REPORTSTO  integer,
    BIRTHDATE  date,
    HIREDATE   date,
    ADDRESS    varchar(70) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    CITY       varchar(40) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    STATE      varchar(40) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    COUNTRY    varchar(40) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    POSTALCODE varchar(10) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    PHONE      varchar(24) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    FAX        varchar(24) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    EMAIL      varchar(60) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    CONSTRAINT PK_EMPLOYEE
    PRIMARY KEY (EMPLOYEEID)
)
;
CREATE TABLE CUSTOMER
(
    CUSTOMERID   integer     NOT NULL,
    FIRSTNAME    varchar(40) CHARACTER SET ISO8859_1 NOT NULL COLLATE ISO8859_1,
    LASTNAME     varchar(20) CHARACTER SET ISO8859_1 NOT NULL COLLATE ISO8859_1,
    COMPANY      varchar(80) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    ADDRESS      varchar(70) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    CITY         varchar(40) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    STATE        varchar(40) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    COUNTRY      varchar(40) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    POSTALCODE   varchar(10) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    PHONE        varchar(24) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    FAX          varchar(24) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    EMAIL        varchar(60) CHARACTER SET ISO8859_1 NOT NULL COLLATE ISO8859_1,
    SUPPORTREPID integer,
    CONSTRAINT PK_CUSTOMER
    PRIMARY KEY (CUSTOMERID)
)
;
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT FK_EMPLOYEEREPORTSTO
    FOREIGN KEY (REPORTSTO)
    REFERENCES EMPLOYEE (EMPLOYEEID)
;
CREATE TABLE GENRE
(
    GENREID integer      NOT NULL,
    NAME    varchar(120) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    CONSTRAINT PK_GENRE
    PRIMARY KEY (GENREID)
)
;
CREATE TABLE MEDIATYPE
(
    MEDIATYPEID integer      NOT NULL,
    NAME        varchar(120) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    CONSTRAINT PK_MEDIATYPE
    PRIMARY KEY (MEDIATYPEID)
)
;
CREATE TABLE PLAYLIST
(
    PLAYLISTID integer      NOT NULL,
    NAME       varchar(120) CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    CONSTRAINT PK_PLAYLIST
    PRIMARY KEY (PLAYLISTID)
)
;
CREATE TRIGGER CUSTOMER_BI FOR CUSTOMER
BEFORE INSERT
AS
BEGIN
NEW.CUSTOMERID = GEN_ID(CUSTOMER_GEN, 1);
END
;
ALTER TABLE ALBUM
    ADD CONSTRAINT FK_ALBUMARTISTID
    FOREIGN KEY (ARTISTID)
    REFERENCES ARTIST (ARTISTID)
;
CREATE TABLE TRACK
(
    TRACKID      integer       NOT NULL,
    NAME         varchar(200)  CHARACTER SET ISO8859_1 NOT NULL COLLATE ISO8859_1,
    ALBUMID      integer,
    MEDIATYPEID  integer       NOT NULL,
    GENREID      integer,
    COMPOSER     varchar(220)  CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    MILLISECONDS integer       NOT NULL,
    BYTES        integer,
    UNITPRICE    numeric(10,2) NOT NULL,
    CONSTRAINT PK_TRACK
    PRIMARY KEY (TRACKID)
)
;
ALTER TABLE CUSTOMER
    ADD CONSTRAINT FK_CUSTOMERSUPPORTREPID
    FOREIGN KEY (SUPPORTREPID)
    REFERENCES EMPLOYEE (EMPLOYEEID)
;
CREATE TABLE INVOICE
(
    INVOICEID         integer       NOT NULL,
    CUSTOMERID        integer       NOT NULL,
    INVOICEDATE       date          DEFAULT CURRENT_DATE,
    BILLINGADDRESS    varchar(70)   CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    BILLINGCITY       varchar(40)   CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    BILLINGSTATE      varchar(40)   CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    BILLINGCOUNTRY    varchar(40)   CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    BILLINGPOSTALCODE varchar(10)   CHARACTER SET ISO8859_1 COLLATE ISO8859_1,
    TOTAL             numeric(10,2) NOT NULL,
    CONSTRAINT PK_INVOICE
    PRIMARY KEY (INVOICEID)
)
;
ALTER TABLE TRACK
    ADD CONSTRAINT FK_TRACKGENREID
    FOREIGN KEY (GENREID)
    REFERENCES GENRE (GENREID)
;
CREATE TABLE INVOICELINE
(
    INVOICELINEID integer       NOT NULL,
    INVOICEID     integer       NOT NULL,
    TRACKID       integer       NOT NULL,
    UNITPRICE     numeric(10,2) NOT NULL,
    QUANTITY      integer       NOT NULL,
    CONSTRAINT PK_INVOICELINE
    PRIMARY KEY (INVOICELINEID)
)
;
ALTER TABLE TRACK
    ADD CONSTRAINT FK_TRACKMEDIATYPEID
    FOREIGN KEY (MEDIATYPEID)
    REFERENCES MEDIATYPE (MEDIATYPEID)
;
CREATE TABLE PLAYLISTTRACK
(
    PLAYLISTID integer NOT NULL,
    TRACKID    integer NOT NULL,
    CONSTRAINT PK_PLAYLISTTRACK
    PRIMARY KEY (PLAYLISTID,TRACKID)
)
;
CREATE TRIGGER INVOICE_BI FOR INVOICE
BEFORE INSERT
AS
BEGIN
NEW.INVOICEID = GEN_ID(INVOICE_GEN, 1);
END
;
ALTER TABLE TRACK
    ADD CONSTRAINT FK_TRACKALBUMID
    FOREIGN KEY (ALBUMID)
    REFERENCES ALBUM (ALBUMID)
;
ALTER TABLE INVOICE
    ADD CONSTRAINT FK_INVOICECUSTOMERID
    FOREIGN KEY (CUSTOMERID)
    REFERENCES CUSTOMER (CUSTOMERID)
;
ALTER TABLE INVOICELINE
    ADD CONSTRAINT FK_INVOICELINEINVOICEID
    FOREIGN KEY (INVOICEID)
    REFERENCES INVOICE (INVOICEID)
;
ALTER TABLE INVOICELINE
    ADD CONSTRAINT FK_INVOICELINETRACKID
    FOREIGN KEY (TRACKID)
    REFERENCES TRACK (TRACKID)
;
ALTER TABLE PLAYLISTTRACK
    ADD CONSTRAINT FK_PLAYLISTTRACKPLAYLISTID
    FOREIGN KEY (PLAYLISTID)
    REFERENCES PLAYLIST (PLAYLISTID)
;
ALTER TABLE PLAYLISTTRACK
    ADD CONSTRAINT FK_PLAYLISTTRACKTRACKID
    FOREIGN KEY (TRACKID)
    REFERENCES TRACK (TRACKID)
;
